"""
Shopify Theme API Integration
Manage theme files and add discount percentage badges automatically

API: Shopify Admin API - Themes
"""

from fastapi import APIRouter, HTTPException, Query, Body
from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
import httpx
import os
import re

router = APIRouter(prefix="/api/shopify/themes", tags=["Shopify Themes"])

# Shopify Configuration
SHOPIFY_SHOP_URL = os.environ.get("SHOPIFY_SHOP_URL", "").replace("https://", "").replace("http://", "").rstrip("/")
SHOPIFY_ACCESS_TOKEN = os.environ.get("SHOPIFY_ACCESS_TOKEN", "")
SHOPIFY_API_VERSION = "2024-01"


def get_shopify_headers():
    return {
        "X-Shopify-Access-Token": SHOPIFY_ACCESS_TOKEN,
        "Content-Type": "application/json",
    }


def get_shopify_url(endpoint: str) -> str:
    return f"https://{SHOPIFY_SHOP_URL}/admin/api/{SHOPIFY_API_VERSION}/{endpoint}"


# =============================================================================
# MODELS
# =============================================================================

class UpdateAssetRequest(BaseModel):
    theme_id: int = Field(..., description="Theme ID")
    asset_key: str = Field(..., description="Asset key (e.g., 'snippets/price.liquid')")
    value: str = Field(..., description="New content for the asset")


class AddDiscountBadgeRequest(BaseModel):
    theme_id: int = Field(..., description="Theme ID to update")
    badge_style: str = Field("red", description="Badge color: red, green, black, orange")
    badge_position: str = Field("top-left", description="Position: top-left, top-right, bottom-left, bottom-right")


# =============================================================================
# DISCOUNT BADGE LIQUID CODE
# =============================================================================

DISCOUNT_BADGE_SNIPPET = '''
{%- comment -%}
  Discount Badge Snippet - Auto-generated by TNV Theme API
  Shows percentage discount when compare_at_price exists
{%- endcomment -%}

{%- if product.compare_at_price > product.price -%}
  {%- assign discount_amount = product.compare_at_price | minus: product.price -%}
  {%- assign discount_percent = discount_amount | times: 100.0 | divided_by: product.compare_at_price | round -%}
  <span class="tnv-discount-badge tnv-discount-badge--{{ badge_style | default: 'red' }} tnv-discount-badge--{{ badge_position | default: 'top-left' }}">
    -{{ discount_percent }}%
  </span>
{%- endif -%}
'''

DISCOUNT_BADGE_CSS = '''
/* TNV Discount Badge Styles - Auto-generated */
.tnv-discount-badge {
  position: absolute;
  padding: 4px 8px;
  font-size: 12px;
  font-weight: bold;
  color: white;
  border-radius: 4px;
  z-index: 10;
}

.tnv-discount-badge--red { background-color: #dc2626; }
.tnv-discount-badge--green { background-color: #16a34a; }
.tnv-discount-badge--black { background-color: #000000; }
.tnv-discount-badge--orange { background-color: #ea580c; }

.tnv-discount-badge--top-left { top: 8px; left: 8px; }
.tnv-discount-badge--top-right { top: 8px; right: 8px; }
.tnv-discount-badge--bottom-left { bottom: 8px; left: 8px; }
.tnv-discount-badge--bottom-right { bottom: 8px; right: 8px; }

/* Price display with discount */
.tnv-price-wrapper {
  display: flex;
  align-items: center;
  gap: 8px;
  flex-wrap: wrap;
}

.tnv-price-current {
  font-weight: bold;
  font-size: 1.1em;
}

.tnv-price-compare {
  text-decoration: line-through;
  color: #9ca3af;
  font-size: 0.9em;
}

.tnv-price-discount {
  background-color: #fef2f2;
  color: #dc2626;
  padding: 2px 6px;
  border-radius: 4px;
  font-size: 0.85em;
  font-weight: 600;
}
'''

PRICE_WITH_DISCOUNT_SNIPPET = '''
{%- comment -%}
  Price Display with Discount Percentage - Auto-generated by TNV Theme API
{%- endcomment -%}

<div class="tnv-price-wrapper">
  <span class="tnv-price-current">{{ product.price | money }}</span>
  
  {%- if product.compare_at_price > product.price -%}
    <span class="tnv-price-compare">{{ product.compare_at_price | money }}</span>
    
    {%- assign discount_amount = product.compare_at_price | minus: product.price -%}
    {%- assign discount_percent = discount_amount | times: 100.0 | divided_by: product.compare_at_price | round -%}
    <span class="tnv-price-discount">-{{ discount_percent }}% OFF</span>
  {%- endif -%}
</div>
'''


# =============================================================================
# API ENDPOINTS
# =============================================================================

@router.get("/")
async def list_themes():
    """
    List all themes in the Shopify store.
    Returns published and unpublished themes.
    """
    if not SHOPIFY_SHOP_URL or not SHOPIFY_ACCESS_TOKEN:
        raise HTTPException(status_code=400, detail="Shopify credentials not configured")
    
    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.get(
                get_shopify_url("themes.json"),
                headers=get_shopify_headers()
            )
            
            if response.status_code != 200:
                raise HTTPException(status_code=response.status_code, detail=response.text)
            
            data = response.json()
            themes = data.get("themes", [])
            
            return {
                "success": True,
                "themes": [
                    {
                        "id": t.get("id"),
                        "name": t.get("name"),
                        "role": t.get("role"),  # main = published, unpublished, demo
                        "theme_store_id": t.get("theme_store_id"),
                        "previewable": t.get("previewable"),
                        "created_at": t.get("created_at"),
                        "updated_at": t.get("updated_at"),
                    }
                    for t in themes
                ],
                "published_theme": next((t for t in themes if t.get("role") == "main"), None)
            }
            
    except httpx.TimeoutException:
        raise HTTPException(status_code=504, detail="Shopify API timeout")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/{theme_id}/assets")
async def list_theme_assets(
    theme_id: int,
    filter_type: Optional[str] = Query(None, description="Filter by type: liquid, css, js, json")
):
    """
    List all assets in a theme.
    """
    if not SHOPIFY_SHOP_URL or not SHOPIFY_ACCESS_TOKEN:
        raise HTTPException(status_code=400, detail="Shopify credentials not configured")
    
    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.get(
                get_shopify_url(f"themes/{theme_id}/assets.json"),
                headers=get_shopify_headers()
            )
            
            if response.status_code != 200:
                raise HTTPException(status_code=response.status_code, detail=response.text)
            
            data = response.json()
            assets = data.get("assets", [])
            
            # Filter by type if specified
            if filter_type:
                assets = [a for a in assets if a.get("key", "").endswith(f".{filter_type}")]
            
            # Group by folder
            grouped = {}
            for asset in assets:
                key = asset.get("key", "")
                folder = key.split("/")[0] if "/" in key else "root"
                if folder not in grouped:
                    grouped[folder] = []
                grouped[folder].append({
                    "key": key,
                    "content_type": asset.get("content_type"),
                    "size": asset.get("size"),
                    "updated_at": asset.get("updated_at"),
                })
            
            return {
                "success": True,
                "theme_id": theme_id,
                "total_assets": len(assets),
                "assets_by_folder": grouped,
                "price_related_files": [
                    a for a in assets 
                    if any(term in a.get("key", "").lower() for term in ["price", "product", "card", "badge"])
                ]
            }
            
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/{theme_id}/assets/content")
async def get_asset_content(
    theme_id: int,
    asset_key: str = Query(..., description="Asset key (e.g., 'snippets/price.liquid')")
):
    """
    Get the content of a specific theme asset.
    """
    if not SHOPIFY_SHOP_URL or not SHOPIFY_ACCESS_TOKEN:
        raise HTTPException(status_code=400, detail="Shopify credentials not configured")
    
    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.get(
                get_shopify_url(f"themes/{theme_id}/assets.json"),
                params={"asset[key]": asset_key},
                headers=get_shopify_headers()
            )
            
            if response.status_code != 200:
                raise HTTPException(status_code=response.status_code, detail=response.text)
            
            data = response.json()
            asset = data.get("asset", {})
            
            return {
                "success": True,
                "theme_id": theme_id,
                "key": asset.get("key"),
                "content_type": asset.get("content_type"),
                "size": asset.get("size"),
                "value": asset.get("value"),
                "updated_at": asset.get("updated_at"),
            }
            
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.put("/{theme_id}/assets")
async def update_asset(theme_id: int, request: UpdateAssetRequest):
    """
    Update a theme asset's content.
    
    WARNING: This modifies your live theme. Make a backup first!
    """
    if not SHOPIFY_SHOP_URL or not SHOPIFY_ACCESS_TOKEN:
        raise HTTPException(status_code=400, detail="Shopify credentials not configured")
    
    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.put(
                get_shopify_url(f"themes/{theme_id}/assets.json"),
                headers=get_shopify_headers(),
                json={
                    "asset": {
                        "key": request.asset_key,
                        "value": request.value
                    }
                }
            )
            
            if response.status_code not in [200, 201]:
                raise HTTPException(status_code=response.status_code, detail=response.text)
            
            data = response.json()
            asset = data.get("asset", {})
            
            return {
                "success": True,
                "message": f"Asset '{request.asset_key}' updated successfully",
                "theme_id": theme_id,
                "asset": {
                    "key": asset.get("key"),
                    "updated_at": asset.get("updated_at"),
                }
            }
            
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/add-discount-badge")
async def add_discount_badge(request: AddDiscountBadgeRequest):
    """
    Automatically add discount percentage badges to your theme.
    
    This will:
    1. Create a new snippet: snippets/tnv-discount-badge.liquid
    2. Add CSS styles to assets/tnv-discount.css
    3. Provide instructions for including in your product cards
    """
    if not SHOPIFY_SHOP_URL or not SHOPIFY_ACCESS_TOKEN:
        raise HTTPException(status_code=400, detail="Shopify credentials not configured")
    
    results = {
        "success": True,
        "theme_id": request.theme_id,
        "files_created": [],
        "errors": [],
    }
    
    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            # 1. Create discount badge snippet
            badge_snippet = DISCOUNT_BADGE_SNIPPET.replace(
                "{{ badge_style | default: 'red' }}", 
                f"{{ badge_style | default: '{request.badge_style}' }}"
            ).replace(
                "{{ badge_position | default: 'top-left' }}", 
                f"{{ badge_position | default: '{request.badge_position}' }}"
            )
            
            response = await client.put(
                get_shopify_url(f"themes/{request.theme_id}/assets.json"),
                headers=get_shopify_headers(),
                json={
                    "asset": {
                        "key": "snippets/tnv-discount-badge.liquid",
                        "value": badge_snippet
                    }
                }
            )
            
            if response.status_code in [200, 201]:
                results["files_created"].append("snippets/tnv-discount-badge.liquid")
            else:
                results["errors"].append(f"Failed to create badge snippet: {response.text}")
            
            # 2. Create price with discount snippet
            response = await client.put(
                get_shopify_url(f"themes/{request.theme_id}/assets.json"),
                headers=get_shopify_headers(),
                json={
                    "asset": {
                        "key": "snippets/tnv-price-with-discount.liquid",
                        "value": PRICE_WITH_DISCOUNT_SNIPPET
                    }
                }
            )
            
            if response.status_code in [200, 201]:
                results["files_created"].append("snippets/tnv-price-with-discount.liquid")
            else:
                results["errors"].append(f"Failed to create price snippet: {response.text}")
            
            # 3. Create CSS file
            response = await client.put(
                get_shopify_url(f"themes/{request.theme_id}/assets.json"),
                headers=get_shopify_headers(),
                json={
                    "asset": {
                        "key": "assets/tnv-discount.css",
                        "value": DISCOUNT_BADGE_CSS
                    }
                }
            )
            
            if response.status_code in [200, 201]:
                results["files_created"].append("assets/tnv-discount.css")
            else:
                results["errors"].append(f"Failed to create CSS: {response.text}")
        
        results["instructions"] = [
            "Files created successfully! Now you need to:",
            "",
            "1. Add CSS to your theme.liquid (in <head> section):",
            "   {{ 'tnv-discount.css' | asset_url | stylesheet_tag }}",
            "",
            "2. Add discount badge to product cards:",
            "   {% render 'tnv-discount-badge', product: product %}",
            "",
            "3. Or replace price display with:",
            "   {% render 'tnv-price-with-discount', product: product %}",
            "",
            "4. For product grid/card templates, find your product-card snippet",
            "   and add the badge inside the product image container.",
        ]
        
        return results
            
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/auto-inject-discount-badge")
async def auto_inject_discount_badge(
    theme_id: int = Query(..., description="Theme ID"),
    dry_run: bool = Query(True, description="If true, show what would change without applying")
):
    """
    Automatically find and modify product card templates to include discount badges.
    
    This scans common template locations and injects the discount badge code.
    
    WARNING: This modifies theme files. Use dry_run=true first to preview changes!
    """
    if not SHOPIFY_SHOP_URL or not SHOPIFY_ACCESS_TOKEN:
        raise HTTPException(status_code=400, detail="Shopify credentials not configured")
    
    # Common files that might contain product cards
    target_files = [
        "snippets/product-card.liquid",
        "snippets/card-product.liquid",
        "snippets/product-item.liquid",
        "snippets/product-grid-item.liquid",
        "sections/product-grid.liquid",
        "sections/collection-template.liquid",
        "sections/featured-collection.liquid",
        "templates/collection.liquid",
    ]
    
    results = {
        "theme_id": theme_id,
        "dry_run": dry_run,
        "files_scanned": 0,
        "files_found": [],
        "files_modified": [],
        "changes": [],
        "errors": [],
    }
    
    try:
        async with httpx.AsyncClient(timeout=60.0) as client:
            # First, ensure the badge snippets exist
            if not dry_run:
                # Create the badge snippet
                await client.put(
                    get_shopify_url(f"themes/{theme_id}/assets.json"),
                    headers=get_shopify_headers(),
                    json={
                        "asset": {
                            "key": "snippets/tnv-discount-badge.liquid",
                            "value": DISCOUNT_BADGE_SNIPPET
                        }
                    }
                )
                
                # Create CSS
                await client.put(
                    get_shopify_url(f"themes/{theme_id}/assets.json"),
                    headers=get_shopify_headers(),
                    json={
                        "asset": {
                            "key": "assets/tnv-discount.css",
                            "value": DISCOUNT_BADGE_CSS
                        }
                    }
                )
            
            # Scan each target file
            for file_key in target_files:
                results["files_scanned"] += 1
                
                try:
                    response = await client.get(
                        get_shopify_url(f"themes/{theme_id}/assets.json"),
                        params={"asset[key]": file_key},
                        headers=get_shopify_headers()
                    )
                    
                    if response.status_code != 200:
                        continue
                    
                    data = response.json()
                    asset = data.get("asset", {})
                    content = asset.get("value", "")
                    
                    if not content:
                        continue
                    
                    results["files_found"].append(file_key)
                    
                    # Check if already has our badge
                    if "tnv-discount-badge" in content:
                        results["changes"].append({
                            "file": file_key,
                            "action": "skipped",
                            "reason": "Already has TNV discount badge"
                        })
                        continue
                    
                    # Look for product image container patterns
                    # Common patterns: <div class="product-card__image">, <div class="card__media">, etc.
                    image_patterns = [
                        (r'(<div[^>]*class="[^"]*product[^"]*image[^"]*"[^>]*>)', r'\1\n  {% render \'tnv-discount-badge\', product: product %}'),
                        (r'(<div[^>]*class="[^"]*card[^"]*media[^"]*"[^>]*>)', r'\1\n  {% render \'tnv-discount-badge\', product: product %}'),
                        (r'(<div[^>]*class="[^"]*card[^"]*image[^"]*"[^>]*>)', r'\1\n  {% render \'tnv-discount-badge\', product: product %}'),
                        (r'(<a[^>]*class="[^"]*product[^"]*link[^"]*"[^>]*>)', r'\1\n  {% render \'tnv-discount-badge\', product: product %}'),
                    ]
                    
                    modified_content = content
                    pattern_matched = False
                    
                    for pattern, replacement in image_patterns:
                        if re.search(pattern, content, re.IGNORECASE):
                            modified_content = re.sub(pattern, replacement, content, count=1, flags=re.IGNORECASE)
                            pattern_matched = True
                            break
                    
                    if pattern_matched and modified_content != content:
                        results["changes"].append({
                            "file": file_key,
                            "action": "would_modify" if dry_run else "modified",
                            "preview": modified_content[:500] + "..." if len(modified_content) > 500 else modified_content
                        })
                        
                        if not dry_run:
                            # Actually update the file
                            update_response = await client.put(
                                get_shopify_url(f"themes/{theme_id}/assets.json"),
                                headers=get_shopify_headers(),
                                json={
                                    "asset": {
                                        "key": file_key,
                                        "value": modified_content
                                    }
                                }
                            )
                            
                            if update_response.status_code in [200, 201]:
                                results["files_modified"].append(file_key)
                            else:
                                results["errors"].append(f"Failed to update {file_key}: {update_response.text}")
                    else:
                        results["changes"].append({
                            "file": file_key,
                            "action": "no_match",
                            "reason": "Could not find suitable injection point"
                        })
                        
                except Exception as e:
                    results["errors"].append(f"Error processing {file_key}: {str(e)}")
        
        results["success"] = len(results["errors"]) == 0
        results["summary"] = {
            "files_scanned": results["files_scanned"],
            "files_found": len(results["files_found"]),
            "files_modified": len(results["files_modified"]) if not dry_run else 0,
            "would_modify": len([c for c in results["changes"] if c.get("action") == "would_modify"])
        }
        
        if dry_run:
            results["next_step"] = "Run with dry_run=false to apply changes"
        
        return results
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/config")
async def get_theme_config():
    """Check Shopify theme API configuration status"""
    return {
        "shop_url": SHOPIFY_SHOP_URL,
        "token_configured": bool(SHOPIFY_ACCESS_TOKEN),
        "api_version": SHOPIFY_API_VERSION,
        "endpoints": {
            "list_themes": "GET /api/shopify/themes/",
            "list_assets": "GET /api/shopify/themes/{theme_id}/assets",
            "get_asset": "GET /api/shopify/themes/{theme_id}/assets/content?asset_key=...",
            "update_asset": "PUT /api/shopify/themes/{theme_id}/assets",
            "add_discount_badge": "POST /api/shopify/themes/add-discount-badge",
            "auto_inject": "POST /api/shopify/themes/auto-inject-discount-badge",
        }
    }
